# Generated by Django 6.0.7 on 2026-08-05 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='banner_url',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('WORKSHOP', 'Workshop'), ('ENTERTAINMENT', 'Entertainment'), ('SPORTS', 'Sports')], default='MUSIC', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_payout_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='PUBLISHED', max_length=20),
        ),
    ]
