# Generated by Django 6.0.7 on 2026-08-17

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventService',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('provider_name', models.CharField(max_length=200)),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('VENUE', 'Venue'),
                            ('CATERING', 'Catering'),
                            ('SOUND_LIGHT', 'Sound and light'),
                            ('DECORATION', 'Decoration'),
                            ('STAFF', 'Staff'),
                            ('MEDIA', 'Media'),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    'quality_level',
                    models.CharField(
                        choices=[
                            ('ECONOMY', 'Economy'),
                            ('STANDARD', 'Standard'),
                            ('PREMIUM', 'Premium'),
                        ],
                        max_length=20,
                    ),
                ),
                ('location', models.CharField(max_length=200)),
                (
                    'pricing_unit',
                    models.CharField(
                        choices=[
                            ('PACKAGE', 'Package'),
                            ('PER_PERSON', 'Per person'),
                            ('PER_HOUR', 'Per hour'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'min_price',
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    'max_price',
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ('min_capacity', models.PositiveIntegerField()),
                ('max_capacity', models.PositiveIntegerField()),
                (
                    'included_duration_hours',
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ('description', models.TextField()),
                (
                    'source_url',
                    models.URLField(blank=True, default='', max_length=500),
                ),
                ('verified_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'quality_level', 'code'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='audience',
            field=models.CharField(
                choices=[
                    ('CUSTOMER', 'Customer'),
                    ('ORGANIZER', 'Organizer'),
                    ('ALL', 'All'),
                ],
                default='ALL',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='category',
            field=models.CharField(
                choices=[
                    ('GENERAL', 'General'),
                    ('POLICY', 'Policy'),
                    ('PLANNING', 'Planning'),
                    ('SERVICE', 'Service'),
                ],
                default='GENERAL',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='source_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(
                choices=[('USER', 'User'), ('ASSISTANT', 'Assistant')],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                (
                    'embedding',
                    pgvector.django.vector.VectorField(dimensions=768),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'knowledge',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chunks',
                        to='ai_agent.knowledgebase',
                    ),
                ),
            ],
            options={
                'ordering': ['knowledge_id', 'chunk_index'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('knowledge', 'chunk_index'),
                        name='unique_knowledge_chunk_index',
                    ),
                ],
            },
        ),
    ]
