# Generated by Django 6.0.7 on 2026-07-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.tickettype')),
            ],
        ),
    ]
