# Generated by Django 6.0.7 on 2026-08-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_and_more'),
        ('orders', '0004_order_expires_at_order_updated_at_payment_updated_at_and_more'),
        ('seating', '0003_alter_seat_unique_together_seat_locked_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='locked_by_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_seats', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['event', 'status'], name='seating_sea_event_i_f87714_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['status', 'locked_until'], name='seating_sea_status_4b8fa4_idx'),
        ),
    ]
