# Generated by Django 6.0.7 on 2026-07-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
