# Generated by Django 6.0.7 on 2026-08-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_and_more'),
        ('seating', '0002_seat_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('event', 'row', 'number')},
        ),
        migrations.AddField(
            model_name='seat',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.RemoveField(
            model_name='seat',
            name='updated_at',
        ),
    ]
